### PR TITLE
Fix image capture

### PR DESCRIPTION
**Pull request by monich**
There's no need for D-Bus, `QQuickWindow::grabWindow()` does the job. Also, moved camera to QML. There's no need to maintain native `QCamera`.

Please give it a try and update the version in Jolla store if you are OK with the solution.

### CODE REVIEW

**Comment by steffen-foerster** [comment]
Hi Slava

Thank you for your improvements. I'm no longer maintain the project. Do you want to become the app owner in the Jolla Store? I can ask the Jolla support to move the Codereader app to your account. 

Cheers,
Steffen

**Comment by monich** [comment]
Go ahead. It's a useful app, I would like to keep it working. My username in Jolla Store is **slava**.

**Comment by steffen-foerster** [comment]
Hi Slava

Jolla's developer support doesn't respond. Fell free to register the code as a new application in the Jolla store. Change the name harbour-barcode and it should work. 

Cheers,
Steffen

**Comment by monich** [comment]
Oh wait, I'm from Jolla myself! Let me ping somebody...

**Comment by monich** [comment]
Done! It's mine :) Should I make releases off my own fork then?

**Comment by steffen-foerster** [comment]
Good news! Yes, you can use your fork to make new releases. Thanks for maintain the application in the future!

**Comment by monich** [comment]
OK, I'll merge this fix to my own fork then! Closing this one.

**Comment by Olf0** [comment]
@monich: Hi Slava, can you please enable the "Issues" section in your fork of CodeReader at GitHub then, as it does not seem to make much sense to submit issues here in @steffen-foerster's repository (especially for v1.0.0).

**Comment by monich** [comment]
Done!

**Pull request closed without merging**
